### ISSUE TITLE
Export from H2-database fails

### ISSUE THREAD

**Issue by BBATools** [sfa-siard/SiardCmd#7]
I've tried exporting to siard from two different H2-databases. They both fail with the same exception.
See complete log underneath. Is it at problem with the new MVStore storage? I see your testfiles are called h2.db, so presumably they use the old H2 storage. But that could be completely unrelated,
Also, I guess it's av bug that you're forced to use the -u and -p switches when the database itself doesn't need a username and password. 

C:\Arkimint\portable_siardcmd-2.1.54>siardfromdb.cmd -o -j=jdbc:h2:D:\bkdok\bkdo
kFullstendig.mv.db -u=INNSYN_TEST -p=hemmelig -s=%execdir%\_DATA\uttrekk.siard -
x=%execdir%\_DATA\lobs\
Aktiv tegntabell: 1252
SiardFromDb 2.1.54 - Program to store database content in a .siard file
SIARD Suite 2.1: (c) Swiss Federal Archives, Berne, Switzerland, 2008-2016
Specified by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Andreas Voss, Swiss Federal Archives, Berne, Switzerland
               Anders Bo Nielsen, Danish National Archives, Denmark
               Claire Röthlisberger-Jourdan, KOST, Berne, Switzerland
Developed by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Simon Jutz, Cytex GmbH, Zurich, Switzerland
Tested by    : Claudia Matthys, POOL Computer AG, Zurich, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Yvan Dutoit, Swiss Federal Archives, Berne, Switzerland
Managed by   : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Alain Mast, Swiss Federal Archives, Berne, Switzerland
               Krystyna Ohnesorge, Swiss Federal Archives, Berne, Switzerland
JAVA         : Version 1.8.0_151-1-ojdkbuild (64)
Windows 7    : Version 6.1 (amd64)

Parameters
  JDBC URL               : jdbc:h2:D:\bkdok\bkdokFullstendig.mv.db
  Database user          : INNSYN_TEST
  Database password      : ***
  SIARD file             : C:\Arkimint\portable_siardcmd-2.1.54\_DATA\uttrekk.si
ard
  External LOB folder    : file:///C:/Arkimint/portable_siardcmd-2.1.54/_DATA/lo
bs/

Connected to jdbc:h2:D:\bkdok\bkdokFullstendig.mv.db
Meta Data
No LOB column found to be externalized!

Primary Data

Download terminated successfully.
E 2018.06.26 13:46:30: XML validation for null failed at line -1 and column -1 w
ith message cvc-complex-type.2.4.b: The content of element 'schemas' is not comp
lete. One of '{"http://www.bar.admin.ch/xmlns/siard/2/metadata.xsd":schema}' is
expected.
  java.io.IOException: Error exporting metadata!< javax.xml.bind.MarshalExceptio
n: < org.xml.sax.SAXParseException: cvc-complex-type.2.4.b: The content of eleme
nt 'schemas' is not complete. One of '{"http://www.bar.admin.ch/xmlns/siard/2/me
tadata.xsd":schema}' is expected.

C:\Arkimint\portable_siardcmd-2.1.54>

**Comment by mortenee** [comment]
I did some more testing and see that I get the same error with "testfiles/conn" from sfa-siard/JdbcH2.
Also did some debugging and it seems like _archive.getSchemas() returns zero schemas for some reason.

**Comment by HartwigThomas** [comment]
My impression is, that your first problem comes from the fact, that (as the message says) no LOB column could be found for export and then no tables were exported.
You are right, that the database in testfiles/conn returned the same error.
That is a consequence of its being completely empty.
The testfiles folder should (and will) really be deleted, because the test database is always created on the fly.
The test databases generated by the JUnit tests in tmp work fine.

The previous versions of SIARD did not handle exported LOB columns correctly. So your first problem is possibly a result of that. In the current version I have fixed all problems with exporting LOB columns and have extended the documentation adding examples for LOB column export.

Please try the export again with the current SIARD version.

**Comment by HartwigThomas** [comment]
I need to correct the above: The empty databases are actually used for creating the test databases.
Nevertheless they will be replaced by "full" databases in order to make it possible to test SIARD with them.

**Comment by HartwigThomas** [comment]
Without an example database reproducing the problem, this issue cannot be handled and is therefore closed.

**Comment by mortenee** [comment]
I finally had some time to do some more testing on this problem and I got a bit further than last time. It seems the problem is essentially that siardCmd works with the old 1.3 version of H2 but not the newer 1.4 version. 

See below for test results (see comment for each section).

#################################################################################
# Original test - same as in june with new version og siardcmd
./siardfromdb.sh -o -j=jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn.h2.db -u=bba -p=bba -s=/home/bba/_DATA/uttrekk.siard
SiardFromDb 2.1.120 - Program to store database content in a .siard file
SIARD Suite 2.1: (c) Swiss Federal Archives, Berne, Switzerland, 2008-2016
Specified by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Andreas Voss, Swiss Federal Archives, Berne, Switzerland
               Anders Bo Nielsen, Danish National Archives, Denmark
               Claire Röthlisberger-Jourdan, KOST, Berne, Switzerland
Developed by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Simon Jutz, Cytex GmbH, Zurich, Switzerland
Tested by    : Claudia Matthys, POOL Computer AG, Zurich, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Yvan Dutoit, Swiss Federal Archives, Berne, Switzerland
Managed by   : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Alain Mast, Swiss Federal Archives, Berne, Switzerland
               Krystyna Ohnesorge, Swiss Federal Archives, Berne, Switzerland
JAVA         : Version 1.8.0_191 (64)
Linux        : Version 4.15.0-42-generic (amd64)

Parameters
  JDBC URL               : jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn.h2.db
  Database user          : bba
  Database password      : ***
  SIARD file             : /home/bba/_DATA/uttrekk.siard

Connected to jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn.h2.db
Meta Data

Primary Data

Download terminated successfully.
  java.io.IOException: Error exporting metadata!< javax.xml.bind.MarshalException: < org.xml.sax.SAXParseException: cvc-complex-type.2.4.b: The content of element 'schemas' is not complete. One of '{"http://www.bar.admin.ch/xmlns/siard/2/metadata.xsd":schema}' is expected.

#################################################################################
# Tested replacing h2-1.3.176.jar with h2-1.4.197.jar:
 ./siardfromdb.sh -o -j=jdbc:h2:/media/sf_D_DRIVE/subsystem_test/documentation/subsystem_test  -u=bba -p=bba -x=/home/bba/_DATA/lobs -s=/home/bba/_DATA/uttrekk.siard
SiardFromDb 2.1.120 - Program to store database content in a .siard file
SIARD Suite 2.1: (c) Swiss Federal Archives, Berne, Switzerland, 2008-2016
Specified by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Andreas Voss, Swiss Federal Archives, Berne, Switzerland
               Anders Bo Nielsen, Danish National Archives, Denmark
               Claire Röthlisberger-Jourdan, KOST, Berne, Switzerland
Developed by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Simon Jutz, Cytex GmbH, Zurich, Switzerland
Tested by    : Claudia Matthys, POOL Computer AG, Zurich, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Yvan Dutoit, Swiss Federal Archives, Berne, Switzerland
Managed by   : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Alain Mast, Swiss Federal Archives, Berne, Switzerland
               Krystyna Ohnesorge, Swiss Federal Archives, Berne, Switzerland
JAVA         : Version 1.8.0_191 (64)
Linux        : Version 4.15.0-42-generic (amd64)
  java.lang.Error: java.lang.ClassNotFoundException: org.h2.Driver< java.lang.ClassNotFoundException: org.h2.Driver


#################################################################################
# Test with h2 database created with h2-1.4.197.jar
# original extension mv.db -> renamed to h2.mv since it was impossible to connect otherwise

 ./siardfromdb.sh -o -j=jdbc:h2:/media/sf_D_DRIVE/subsystem_test/documentation/subsystem_test  -u=bba -p=bba -x=/home/bba/_DATA/lobs -s=/home/bba/_DATA/uttrekk.siard
SiardFromDb 2.1.120 - Program to store database content in a .siard file
SIARD Suite 2.1: (c) Swiss Federal Archives, Berne, Switzerland, 2008-2016
Specified by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Andreas Voss, Swiss Federal Archives, Berne, Switzerland
               Anders Bo Nielsen, Danish National Archives, Denmark
               Claire Röthlisberger-Jourdan, KOST, Berne, Switzerland
Developed by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Simon Jutz, Cytex GmbH, Zurich, Switzerland
Tested by    : Claudia Matthys, POOL Computer AG, Zurich, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Yvan Dutoit, Swiss Federal Archives, Berne, Switzerland
Managed by   : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Alain Mast, Swiss Federal Archives, Berne, Switzerland
               Krystyna Ohnesorge, Swiss Federal Archives, Berne, Switzerland
JAVA         : Version 1.8.0_191 (64)
Linux        : Version 4.15.0-42-generic (amd64)

Parameters
  JDBC URL               : jdbc:h2:/media/sf_D_DRIVE/subsystem_test/documentation/subsystem_test
  Database user          : bba
  Database password      : ***
  SIARD file             : /home/bba/_DATA/uttrekk.siard
  External LOB folder    : ../lobs/

  org.h2.jdbc.JdbcSQLException: Unsupported database file version or invalid file header in file "/media/sf_D_DRIVE/subsystem_test/documentation/subsystem_test.h2.db" [90048-176]


#################################################################################
# Test with your data test database (conn)

./siardfromdb.sh -o -j=jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn -u="sa" -p="sapwd" -s=/home/bba/_DATA/uttrekk.siardSiardFromDb 2.1.120 - Program to store database content in a .siard file
SIARD Suite 2.1: (c) Swiss Federal Archives, Berne, Switzerland, 2008-2016
Specified by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Andreas Voss, Swiss Federal Archives, Berne, Switzerland
               Anders Bo Nielsen, Danish National Archives, Denmark
               Claire Röthlisberger-Jourdan, KOST, Berne, Switzerland
Developed by : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Simon Jutz, Cytex GmbH, Zurich, Switzerland
Tested by    : Claudia Matthys, POOL Computer AG, Zurich, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Yvan Dutoit, Swiss Federal Archives, Berne, Switzerland
Managed by   : Hartwig Thomas, Enter AG, Rüti ZH, Switzerland
               Marcel Büchler, Swiss Federal Archives, Berne, Switzerland
               Alain Mast, Swiss Federal Archives, Berne, Switzerland
               Krystyna Ohnesorge, Swiss Federal Archives, Berne, Switzerland
JAVA         : Version 1.8.0_191 (64)
Linux        : Version 4.15.0-42-generic (amd64)

Parameters
  JDBC URL               : jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn
  Database user          : sa
  Database password      : ***
  SIARD file             : /home/bba/_DATA/uttrekk.siard

Connected to jdbc:h2:/home/bba/Downloads/JdbcH2-master/testfiles/conn
Meta Data
  Table: TESTH2SCHEMA.TH2COMPLEX
  Table: TESTH2SCHEMA.TH2SIMPLE
  Table: TESTSQLSCHEMA.TSQLCOMPLEX
  Table: TESTSQLSCHEMA.TSQLSIMPLE
  View: TESTSQLSCHEMA.VSQLSIMPLE

Primary Data
  Table: TESTH2SCHEMA.TH2COMPLEX
    Record 1 (0.00 kB/s)
    Total: 1 records (0 bytes in 98 ms)
  Table: TESTH2SCHEMA.TH2SIMPLE
    Record 1 (0.00 kB/s)
    Total: 1 records (0 bytes in 56 ms)
  Table: TESTSQLSCHEMA.TSQLCOMPLEX
    Record 1 (0.00 kB/s)
    Total: 1 records (0 bytes in 12 ms)
  Table: TESTSQLSCHEMA.TSQLSIMPLE
    Record 1 (0.00 kB/s)
    Total: 1 records (0 bytes in 257 ms)

Download terminated successfully.
SiardFromDb 2.1.120 terminates.
